# Generated by Django 3.1.2 on 2021-02-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='flat_no',
        ),
        migrations.AddField(
            model_name='customuser',
            name='npi',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
