# Generated by Django 3.1.2 on 2021-02-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210217_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rights',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='npi',
            field=models.CharField(max_length=10),
        ),
    ]
