# Generated by Django 3.1.2 on 2021-02-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210221_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='npi',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
