# Generated by Django 3.1.2 on 2021-03-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='label',
            field=models.CharField(default='notsuspicious', max_length=50),
        ),
    ]
