# Generated by Django 3.1.2 on 2021-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0003_auto_20210315_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='data',
            name='created',
        ),
        migrations.RemoveField(
            model_name='data',
            name='inprogress',
        ),
        migrations.AddField(
            model_name='data',
            name='documentver',
            field=models.CharField(default='ND', max_length=10),
        ),
    ]
