# Generated by Django 3.1.2 on 2021-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0004_auto_20210316_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='claimid',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='npi',
            field=models.IntegerField(max_length=100),
        ),
    ]
