# Generated by Django 3.1.2 on 2021-03-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0005_auto_20210316_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Average_Supplier_Submitted_max',
            new_name='Average_Supplier_Submitted_Charge_max',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Average_Supplier_Submitted_median',
            new_name='Average_Supplier_Submitted_Charge_median',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Average_Supplier_Submitted_min',
            new_name='Average_Supplier_Submitted_Charge_min',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Average_Supplier_Submitted_std',
            new_name='Average_Supplier_Submitted_Charge_std',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Average_Supplier_Submitted_sum',
            new_name='Average_Supplier_Submitted_Charge_sum',
        ),
        migrations.AlterField(
            model_name='data',
            name='claimid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='npi',
            field=models.IntegerField(),
        ),
    ]
