# Generated by Django 3.1.2 on 2021-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0006_auto_20210317_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='claimid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
